import React from 'react'
import './Links.css'
import { Container } from 'react-grid-system';

export default function Links(){
    return(
        <Container style={{backgroundColor: 'white'}}>
                <div className="imprensa-links">
                            <h3>Veja aqui algumas matérias já publicadas que mencionam o Bossa Criativa na imprensa</h3>
                            <p><a href="https://plantaodoslagos.com.br/categoria/cidades/bossa-criativa-reune-oficinas-de-arte-gratis-pela-internet/" target="_blank" rel="noopener noreferrer">https://plantaodoslagos.com.br/categoria/cidades/bossa-criativa-reune-oficinas-de-arte-gratis-pela-internet/</a></p>
                                <p><a href="https://veja.abril.com.br/blog/radar/bossa-criativa-reune-oficinais-de-arte-gratis-pela-internet/
" target="_blank" rel="noopener noreferrer">https://veja.abril.com.br/blog/radar/bossa-criativa-reune-oficinais-de-arte-gratis-pela-internet/
</a></p>
                                <p><a href="https://brazil.shafaqna.com/PT/AL/6791912" target="_blank" rel="noopener noreferrer">https://brazil.shafaqna.com/PT/AL/6791912</a></p>
                                <p><a href="https://www.em.com.br/app/noticia/cultura/2020/06/29/interna_cultura,1160728/yunk-vino-destaque-do-trap-nacional-lanca-237deluxe.shtml" target="_blank" rel="noopener noreferrer">https://www.em.com.br/app/noticia/cultura/2020/06/29/interna_cultura,1160728/yunk-vino-destaque-do-trap-nacional-lanca-237deluxe.shtml</a></p>
                                <p><a href="https://movimento.com/funarte-bossa-criativa-arte-de-toda-gente/" target="_blank" rel="noopener noreferrer">https://movimento.com/funarte-bossa-criativa-arte-de-toda-gente/</a></p>
                                <p><a href="https://www.orzil.org/noticias/em-live-funarte-e-ufrj-lancam-projeto-bossa-criativa/" target="_blank" rel="noopener noreferrer">https://www.orzil.org/noticias/em-live-funarte-e-ufrj-lancam-projeto-bossa-criativa/</a></p>
                                <p><a href="https://www.revistaprosaversoearte.com/em-live-funarte-e-ufrj-lancam-projeto-bossa-criativa-arte-de-toda-gente/" target="_blank" rel="noopener noreferrer">https://www.revistaprosaversoearte.com/em-live-funarte-e-ufrj-lancam-projeto-bossa-criativa-arte-de-toda-gente/</a></p>
                                <p><a href="https://www.blognovidadesonline.com.br/2020/06/funarte-e-ufrj-lancam-projeto-bossa.html" target="_blank" rel="noopener noreferrer">https://www.blognovidadesonline.com.br/2020/06/funarte-e-ufrj-lancam-projeto-bossa.html</a></p>
                                <p><a href="https://dicadeteatro.com.br/funarte-e-ufrj-lancam-o-projeto-bossa-criativa/
" target="_blank" rel="noopener noreferrer">https://dicadeteatro.com.br/funarte-e-ufrj-lancam-o-projeto-bossa-criativa/
</a></p>
                                <p><a href="https://agreganews.com.br/funarte-e-ufrj-lancam-projeto-bossa-criativa-em-live/" target="_blank" rel="noopener noreferrer">https://agreganews.com.br/funarte-e-ufrj-lancam-projeto-bossa-criativa-em-live/</a></p>
                                <p><a href="https://www.plurale.com.br/site/agenda-detalhes.php?cod=4103&q=Funarte+e+UFRJ+lan%C3%A7am+o+projeto+Bossa+Criativa&bsc=ativar" target="_blank" rel="noopener noreferrer">https://www.plurale.com.br/site/agenda-detalhes.php?cod=4103&q=Funarte+e+UFRJ+lan%C3%A7am+o+projeto+Bossa+Criativa&bsc=ativar</a></p>
                                <p><a href="https://blogs.oglobo.globo.com/ancelmo/post/tributo-virtual-aldir-blanc.html?utm_source=aplicativoOGlobo&utm_medium=aplicativo&utm_campaign=compartilha" target="_blank" rel="noopener noreferrer">https://blogs.oglobo.globo.com/ancelmo/post/tributo-virtual-aldir-blanc.html?utm_source=aplicativoOGlobo&utm_medium=aplicativo&utm_campaign=compartilha</a></p>
                                <p><a href="https://www.google.com/amp/s/www.correiobraziliense.com.br/app/noticia/diversao-e-arte/2020/06/26/interna_diversao_arte,867144/amp.html " target="_blank" rel="noopener noreferrer">https://www.google.com/amp/s/www.correiobraziliense.com.br/app/noticia/diversao-e-arte/2020/06/26/interna_diversao_arte,867144/amp.html </a></p>
                                <p><a href="https://www.google.com/amp/s/portalgc.com.br/variedades/bossa-criativa-funarte-promove-projeto-cultural-com-lives-e-oficinas/amp/ " target="_blank" rel="noopener noreferrer">https://www.google.com/amp/s/portalgc.com.br/variedades/bossa-criativa-funarte-promove-projeto-cultural-com-lives-e-oficinas/amp/ </a></p>
                                <p><a href="https://brazil.shafaqna.com/PT/AL/6791912" target="_blank" rel="noopener noreferrer">https://brazil.shafaqna.com/PT/AL/6791912</a></p>
                                <p><a href="http://rdopiniao.com.br/2020/06/26/arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade/ " target="_blank" rel="noopener noreferrer">http://rdopiniao.com.br/2020/06/26/arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade/ </a></p>
                                <p><a href="http://www.turismo.gov.br/últimas-notícias/13584-em-live%2C-funarte-e-ufrj-lançam-projeto-bossa-criativa.html " target="_blank" rel="noopener noreferrer">http://www.turismo.gov.br/últimas-notícias/13584-em-live%2C-funarte-e-ufrj-lançam-projeto-bossa-criativa.html </a></p>
                                <p><a href="https://www.brasilfashionnews.com.br/arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade/ " target="_blank" rel="noopener noreferrer">https://www.brasilfashionnews.com.br/arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade/ </a></p>
                                <p><a href="https://lulacerda.ig.com.br/cristovao-bastos-compositor-e-pianista-faz-homenagem-virtual-a-aldir-blanc/" target="_blank" rel="noopener noreferrer">https://lulacerda.ig.com.br/cristovao-bastos-compositor-e-pianista-faz-homenagem-virtual-a-aldir-blanc/</a></p>
                                <p><a href="https://maricajaplay.com/2020/06/28/arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade/ " target="_blank" rel="noopener noreferrer">https://maricajaplay.com/2020/06/28/arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade/ </a></p>
                                <p><a href="http://cultura.gov.br/funarte-e-ufrj-lancam-o-bossa-criativa-arte-de-toda-gente-com-live-no-dia-30/">http://cultura.gov.br/funarte-e-ufrj-lancam-o-bossa-criativa-arte-de-toda-gente-com-live-no-dia-30/</a></p>
                                <p><a href="http://musica.ufrj.br/index.php/comunicacao/noticias/gerais/projeto-bossa-criativa-arte-de-toda-gente-tem-lancamento-com-live-parceria-da-ufrj"></a>http://musica.ufrj.br/index.php/comunicacao/noticias/gerais/projeto-bossa-criativa-arte-de-toda-gente-tem-lancamento-com-live-parceria-da-ufrj</p>
                                <p><a href="https://alelontra.com.br/em-live-funarte-e-ufrj-lancam-projeto-bossa-criativa/">https://alelontra.com.br/em-live-funarte-e-ufrj-lancam-projeto-bossa-criativa/</a></p>
                                <p><a href="https://www.google.com/amp/s/agenciabrasil.ebc.com.br/geral/noticia/2020-06/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet%3famp 
">https://www.google.com/amp/s/agenciabrasil.ebc.com.br/geral/noticia/2020-06/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet%3famp 
</a></p>
                                <p><a href="https://www.blognovidadesonline.com.br/2020/06/funarte-e-ufrj-lancam-projeto-bossa.html?m=1">https://www.blognovidadesonline.com.br/2020/06/funarte-e-ufrj-lancam-projeto-bossa.html?m=1</a></p>
                                <p><a href="https://www.google.com/amp/s/amp.costanorte.com.br/geral/72777/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet ">https://www.google.com/amp/s/amp.costanorte.com.br/geral/72777/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet </a></p>
                                <p><a href="https://www.google.com/amp/s/www.cenariomt.com.br/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/amp">https://www.google.com/amp/s/www.cenariomt.com.br/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/amp</a></p>
                                <p><a href="https://www.google.com/amp/s/www.mixvale.com.br/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet">https://www.google.com/amp/s/www.mixvale.com.br/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet</a></p>
                                <p><a href="https://agenciabrasil.ebc.com.br/geral/noticia/2020-06/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet">https://agenciabrasil.ebc.com.br/geral/noticia/2020-06/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet</a></p>
                                <p><a href="https://aderivaldo23.com/noticias/brasil/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet">https://aderivaldo23.com/noticias/brasil/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet</a></p>
                                <p><a href="http://rdopiniao.com.br/2020/06/26/arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade/ ">http://rdopiniao.com.br/2020/06/26/arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade/ </a></p>
                                <p><a href="https://www.otempo.com.br/diversao/funarte-lanca-projeto-online-com-lives-shows-e-oficinas-de-capacitacao-1.2355012">https://www.otempo.com.br/diversao/funarte-lanca-projeto-online-com-lives-shows-e-oficinas-de-capacitacao-1.2355012</a></p>
                                <p><a href="https://vejasp.abril.com.br/cultura-lazer/funarte-estreia-hoje-espetaculos-e-oficinas-pela-internet/ ">https://vejasp.abril.com.br/cultura-lazer/funarte-estreia-hoje-espetaculos-e-oficinas-pela-internet/ </a></p>
                                <p><a href="https://www.istoedinheiro.com.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/">https://www.istoedinheiro.com.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/</a></p>
                                <p><a href="https://visitebrasilia.com.br/noticia/arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade/ ">https://visitebrasilia.com.br/noticia/arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade/ </a></p>
                                <p><a href="https://www.cenariomt.com.br/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ ">https://www.cenariomt.com.br/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ </a></p>
                                <p><a href="https://www.google.com/url?rct=j&sa=t&url=https://www.dinheirorural.com.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/&ct=ga&cd=CAEYACoTNDI1NzgxOTcwMTg4NDMyMjEwNDIdNzkyMjVlNTU5OWFjMjA2NDpjb20uYnI6cHQ6QlI&usg=AFQjCNFP47axdMw2XZzitSb7ms-oO2rJuQ">https://www.google.com/url?rct=j&sa=t&url=https://www.dinheirorural.com.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/&ct=ga&cd=CAEYACoTNDI1NzgxOTcwMTg4NDMyMjEwNDIdNzkyMjVlNTU5OWFjMjA2NDpjb20uYnI6cHQ6QlI&usg=AFQjCNFP47axdMw2XZzitSb7ms-oO2rJuQ</a></p>
                                <p><a href="https://istoe.com.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ ">https://istoe.com.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ </a></p>
                                <p><a href="https://exame.com/estilo-de-vida/projeto-da-funarte-estreia-hoje-com-espetaculos-e-oficinas-pela-internet/">https://exame.com/estilo-de-vida/projeto-da-funarte-estreia-hoje-com-espetaculos-e-oficinas-pela-internet/</a></p>
                                <p><a href="https://noticias.uol.com.br/ultimas-noticias/agencia-brasil/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet.htm">https://noticias.uol.com.br/ultimas-noticias/agencia-brasil/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet.htm</a></p>
                                <p><a href="https://br.noticias.yahoo.com/projeto-da-funarte-apresenta-espet%C3%A1culos-153700071.html ">https://br.noticias.yahoo.com/projeto-da-funarte-apresenta-espet%C3%A1culos-153700071.html </a></p>
                                <p><a href="https://agora-to.com.br/geral/item/160354-arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade ">https://agora-to.com.br/geral/item/160354-arte-cultura-e-inclusao-tem-como-palco-internet-e-patrimonios-da-humanidade </a></p>
                                <p>Sistema Costa Norte Comunicação  <br/><a href="https://d.costanorte.com.br/geral/72777/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet">https://d.costanorte.com.br/geral/72777/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet</a></p>
                                <p>Correio de Notícias  <br/><a href="http://www.ler.news/tag/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ ">http://www.ler.news/tag/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ </a></p>
                                <p>D24 Am Amazonas  <br/><a href="https://d24am.com/plus/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ ">https://d24am.com/plus/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ </a></p>
                                <p>Agora - Divinópolis (MG) <br/><a href="http://agora.com.vc/noticia/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ ">http://agora.com.vc/noticia/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ </a></p>
                                <p>ISN Portal <br/><a href="https://isnportal.com.br/editorias/brasil/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/">https://isnportal.com.br/editorias/brasil/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/</a></p>
                                <p>Rede Lajeado <br/><a href="https://www.redelajeado.com.br/noticias/2020/06/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ ">https://www.redelajeado.com.br/noticias/2020/06/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ </a></p>
                                <p>Campos Online <br/><a href="https://www.camposonline.info/projeto-da-funarte-bossa-criativa-leva-cultura-pela-internet/ ">https://www.camposonline.info/projeto-da-funarte-bossa-criativa-leva-cultura-pela-internet/ </a></p>
                                <p>Portal de Notícias de Cascavel e Região (Foz do Iguaçu, Toledo) <br/><a href="https://catve.com/2021/noticia/6/294081/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet ">https://catve.com/2021/noticia/6/294081/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet </a></p>
                                <p>O Rolo <br/><a href="https://orolo.com.br/politica/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet">https://orolo.com.br/politica/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet</a></p>
                                <p>Dinheiro Rural  <br/><a href="https://www.dinheirorural.com.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ ">https://www.dinheirorural.com.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ </a></p> 
                                <p>GR News <br/><a href="https://grnews.com.br/30062020/mundo-fama/funarte-apresenta-espetaculos-e-oficinas-pela-internet ">https://grnews.com.br/30062020/mundo-fama/funarte-apresenta-espetaculos-e-oficinas-pela-internet </a></p>
                                <p>Portal da Educativa (MatoGrosso) <br/><a href="http://www.portaldaeducativa.ms.gov.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/">http://www.portaldaeducativa.ms.gov.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/</a></p>
                                <p>Yahoo Esportes <br/><a href="https://esportes.yahoo.com/noticias/projeto-da-funarte-apresenta-espet%C3%A1culos-153700071.html">https://esportes.yahoo.com/noticias/projeto-da-funarte-apresenta-espet%C3%A1culos-153700071.html</a></p>
                                <p><a href="https://www.oliberal.com/cultura/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet-1.281380">https://www.oliberal.com/cultura/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet-1.281380</a></p>
                                <p>Portal do Generoso (Manaus)<br/><a href="https://portaldogeneroso.com/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ 
">https://portaldogeneroso.com/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ 
</a></p>
                                <p>www.oliberal.com <br/><a href="">Projeto da Funarte apresenta espetáculos e oficinas pela internet</a></p>
                                <p>Estreia nesta terça-feria (30) o projeto Bossa Criativa - Arte de Toda Gente, da Fundação Nacional de Artes (Funarte) e da Universidade Federal do Rio de Janeiro (UFRJ). Devido ao isolamento social imposto pela pandemia de covid-19, as apresentações e oficinas com mais de 80 convidados serão . <br/><a href=""></a></p>
                                <p>A Crítica <br/><a href="http://www.acritica.net/editorias/geral/projeto-da-funarte-apresenta-espetaculos-e-oficina-11480879811d6eb5c35/460584/">http://www.acritica.net/editorias/geral/projeto-da-funarte-apresenta-espetaculos-e-oficina-11480879811d6eb5c35/460584/</a></p>                   
                                <p>Jornal de Piracicaba <br/><a href="https://www.jornaldepiracicaba.com.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ ">https://www.jornaldepiracicaba.com.br/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ </a></p>
                                <p>Agora no RS (Rio Grande do Sul) <br/><a href="https://agoranors.com/2020/06/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ ">https://agoranors.com/2020/06/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/ </a></p>
                                <p>O Liberal - Belém PA <br/><a href="https://www.oliberal.com/cultura/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet-1.281380 ">https://www.oliberal.com/cultura/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet-1.281380 </a></p>
                                <p>Blog José Duarte Lima - Princesa Isabel <br/><a href="https://www.duartelima.com.br/109750-projeto-da-funarte-apresenta-espetculos-e-oficinas-pela-internet/">https://www.duartelima.com.br/109750-projeto-da-funarte-apresenta-espetculos-e-oficinas-pela-internet/</a></p>
                                <p>Portal Cantu (Paraná)  <br/><a href="https://portalcantu.com.br/news/basilmundo/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet ">https://portalcantu.com.br/news/basilmundo/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet </a></p>
                                <p>Portal Xeretando (Paraná) <br/><a href="https://xeretando.com.br/noticiaLer/12144">https://xeretando.com.br/noticiaLer/12144</a></p>
                                <p>Alagoas Alerta <br/><a href="https://alagoasalerta.com.br/noticias/cultura/projeto-da-funarte-para-apresentacao-de-espetaculos-e-oficinas-pela-internet-e-inaugurado-nesta-terca-veja-como-assistir ">https://alagoasalerta.com.br/noticias/cultura/projeto-da-funarte-para-apresentacao-de-espetaculos-e-oficinas-pela-internet-e-inaugurado-nesta-terca-veja-como-assistir </a></p>
                                <p>Jornal Dia a Dia (Três Lagoas) <br/><a href="http://jornaldiadia.com.br/2020/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/">http://jornaldiadia.com.br/2020/2020/06/30/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet/</a></p>
                                <p>Painel de Notícias <br/><a href="https://painelnoticias.com.br/cultura/174665/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet ">https://painelnoticias.com.br/cultura/174665/projeto-da-funarte-apresenta-espetaculos-e-oficinas-pela-internet </a></p>
                                <p><a href="https://www.marciapeltier.com.br">https://www.marciapeltier.com.br</a></p> 
                    </div>
            </Container>
    )
}