import React from 'react'
import './Links.css'
import { Container } from 'react-grid-system';

export default function Links(){
    return(
        <Container style={{backgroundColor: 'white'}}>
                <div className="imprensa-links">
                            <h3>Veja aqui algumas matérias já publicadas que mencionam o Bossa Criativa na imprensa</h3>
                                <p><a target="blank" href="https://www.annaramalho.com.br/incentivo-para-as-artes/">https://www.annaramalho.com.br/incentivo-para-as-artes/</a></p>
                                <p><a target="blank" href="https://oglobo.globo.com/cultura/funarte-anuncia-20-milhoes-para-edital-emergencial-lives-com-curadoria-da-escola-de-musica-da-ufrj-24476189 ">https://oglobo.globo.com/cultura/funarte-anuncia-20-milhoes-para-edital-emergencial-lives-com-curadoria-da-escola-de-musica-da-ufrj-24476189 </a></p>
                                <p><a target="blank" href="https://www1.folha.uol.com.br/ilustrada/2020/06/funarte-vai-investir-cerca-de-r-20-mi-em-atividades-culturais.shtml ">https://www1.folha.uol.com.br/ilustrada/2020/06/funarte-vai-investir-cerca-de-r-20-mi-em-atividades-culturais.shtml </a></p>
                                <p><a target="blank" href="https://plantaodoslagos.com.br/categoria/entretenimento/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil-r-20-milhoes/">https://plantaodoslagos.com.br/categoria/entretenimento/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil-r-20-milhoes/</a></p>
                                <p><a target="blank" href="https://movimento.com/funarte-de-toda-gente/">https://movimento.com/funarte-de-toda-gente/</a></p>
                                <p><a target="blank" href="https://www.jcnet.com.br/noticias/cultura/2020/06/726733-funarte-promete-investir-cerca-de-r--20-milhoes-em-atividades-culturais.html">https://www.jcnet.com.br/noticias/cultura/2020/06/726733-funarte-promete-investir-cerca-de-r--20-milhoes-em-atividades-culturais.html</a></p>
                                <p><a target="blank" href="https://dicasdacapital.com.br/lancamento-do-premio-funarte-respirarte-acontece-na-proxima-terca-feira/">https://dicasdacapital.com.br/lancamento-do-premio-funarte-respirarte-acontece-na-proxima-terca-feira/</a></p>
                                <p><a target="blank" href="https://www.tribunadabahiavirtual.com.br/materia/I26831/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil">https://www.tribunadabahiavirtual.com.br/materia/I26831/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil</a></p>
                                <p><a target="blank" href="https://www.trbn.com.br/materia/I26831/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil">https://www.trbn.com.br/materia/I26831/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil</a></p>
                                <p><a target="blank" href="https://www.trbn.com.br/materia/I26831/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil">https://www.trbn.com.br/materia/I26831/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil</a></p>
                                <p><a target="blank" href="https://icarabe.org/node/3840">https://icarabe.org/node/3840</a></p>
                                <p><a target="blank" href="https://www.sopacultural.com/noticias/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil/">https://www.sopacultural.com/noticias/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil/</a></p>
                                <p><a target="blank" href="https://br.noticias.yahoo.com/funarte-anuncia-r-20-milhões-160508834.html">https://br.noticias.yahoo.com/funarte-anuncia-r-20-milhões-160508834.html</a></p>
                                <p><a target="blank" href="https://www.acidadeon.com/NOT,0,0,1524180,Funarte+promete+investir+cerca+de+R+20+milhoes+em+atividades+culturais.aspx">https://www.acidadeon.com/NOT,0,0,1524180,Funarte+promete+investir+cerca+de+R+20+milhoes+em+atividades+culturais.aspx</a></p>
                                <p><a target="blank" href="https://www.folhadelondrina.com.br/folha-2/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades-culturais-2995449e.html">https://www.folhadelondrina.com.br/folha-2/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades-culturais-2995449e.html</a></p>
                                <p><a target="blank" href="https://dlnews.com.br/noticias?id=32790%2Ffunarte-promete-investir-cerca-de-r%24-20-milhoes-em-atividades-culturais#.XueWQlGNWvs">https://dlnews.com.br/noticias?id=32790%2Ffunarte-promete-investir-cerca-de-r%24-20-milhoes-em-atividades-culturais#.XueWQlGNWvs</a></p>
                                <p><a target="blank" href="https://www.selecoes.com.br/plantao/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades-culturais/">https://www.selecoes.com.br/plantao/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades-culturais/</a></p>
                                <p><a target="blank" href="https://revistapaulista.com.br/2020/06/12/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil/">https://revistapaulista.com.br/2020/06/12/funarte-anuncia-investimentos-e-uma-serie-de-acoes-para-todo-o-brasil/</a></p>
                                <p><a target="blank" href="https://www.meionorte.com/blogs/culturaeturismo/funarte-anuncia-investimentos-de-r-20-milhoes-e-acoes-para-o-brasil-343132">https://www.meionorte.com/blogs/culturaeturismo/funarte-anuncia-investimentos-de-r-20-milhoes-e-acoes-para-o-brasil-343132</a></p>
                                <p><a target="blank" href="https://www.mixvale.com.br/2020/06/12/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades-culturais/">https://www.mixvale.com.br/2020/06/12/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades-culturais/</a></p>
                                <p><a target="blank" href="https://riopreto.dlnews.com.br/noticias?id=32790%2Ffunarte-promete-investir-cerca-de-r%24-20-milhoes-em-atividades-culturais#.XueXI8gInKM">https://riopreto.dlnews.com.br/noticias?id=32790%2Ffunarte-promete-investir-cerca-de-r%24-20-milhoes-em-atividades-culturais#.XueXI8gInKM</a></p>
                                <p><a target="blank" href="https://br.financas.yahoo.com/noticias/funarte-promete-investir-cerca-r-234700406.html">https://br.financas.yahoo.com/noticias/funarte-promete-investir-cerca-r-234700406.html</a></p>
                                <p><a target="blank" href="http://www.forumpermanente.org/event_pres/jornadas/jornada-da-quarentena/noticias-jornada-da-quarentena-1/funarte-anuncia-r-20-milhoes-para-edital-emergencial-e-lives-com-curadoria-da-escola-de-musica-da-ufrj">http://www.forumpermanente.org/event_pres/jornadas/jornada-da-quarentena/noticias-jornada-da-quarentena-1/funarte-anuncia-r-20-milhoes-para-edital-emergencial-e-lives-com-curadoria-da-escola-de-musica-da-ufrj</a></p>
                                <p><a target="blank" href="http://www.portaldoholanda.com.br/arte-e-cultura/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades?amp=1">http://www.portaldoholanda.com.br/arte-e-cultura/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades?amp=1</a></p>
                                <p><a target="blank" href="https://www.pirajuiradioclube.com.br/noticia/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades-culturais">https://www.pirajuiradioclube.com.br/noticia/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades-culturais</a></p>
                                <p><a target="blank" href="https://www.jornalfloripa.com.br/geral/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades-culturais/">https://www.jornalfloripa.com.br/geral/funarte-promete-investir-cerca-de-r-20-milhoes-em-atividades-culturais/</a></p>
                                <p>Márcia Peltier <a target="blank" href="www.marciapeltier.com.br">www.marciapeltier.com.br</a>  “... o programa Funarte de Toda Gente, que engloba ações de capacitação e inclusão para a economia criativa - algumas delas em parceria com a UFRJ.”</p>
                                <p><a target="blank" href="https://cultura.am.gov.br/portal/confira-editais-mostras-e-festivais-com-inscricoes-abertas-para-diversas-linguagens-artisticas/">https://cultura.am.gov.br/portal/confira-editais-mostras-e-festivais-com-inscricoes-abertas-para-diversas-linguagens-artisticas/</a></p>
                                <p><a target="blank" href="http://www.fundacaocultural.ba.gov.br/2020/06/14307/Funarte-anuncia-edital-para-Circo-Artes-Visuais-Musica-Danca-Teatro-e-Artes-Integradas.html">http://www.fundacaocultural.ba.gov.br/2020/06/14307/Funarte-anuncia-edital-para-Circo-Artes-Visuais-Musica-Danca-Teatro-e-Artes-Integradas.html</a></p>
                    </div>
            </Container>
    )
}